SportStore.WebUI/Controllers/CartController.cs
using SportStore.Domain.Abstract;
using SportStore.Domain.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SportStore.WebUI.Controllers
{
    public class CartController : Controller
    {
        private IMainRepository mainRepository { get; set; }
        public CartController(IMainRepository mainRepo)
        {
            mainRepository = mainRepo;
        }

        //private Cart GetCart()
        //{
        //    var cart = Session["cart"] as Cart;
        //    if (cart == null)
        //    {
        //        cart = new Cart();
        //        Session["cart"] = cart;
        //    }

        //    return cart;
        //}

        // GET: Cart
        public ActionResult Index(Cart cart, string returnUrl)
        {
            //Cart model = GetCart();
            ViewBag.ReturnUrl = returnUrl;

            return View(cart);
        }

        [HttpPost]
        public ActionResult AddToCart(Cart cart, int productID, string returnUrl)
        {
            var product = mainRepository.Products.FirstOrDefault(x => x.ProductID == productID);
            if (product != null)
            {
                cart.Add(product, 1);
            }

            return RedirectToAction("Index", new { returnUrl });
        }

        [HttpPost]
        public ActionResult RemoveFromCart(Cart cart, int productID, string returnUrl)
        {
            var product = mainRepository.Products.FirstOrDefault(x => x.ProductID == productID);
            if (product != null)
            {
                cart.Remove(product);
            }
            return RedirectToAction("Index", new { returnUrl });
        }

        [HttpPost]
        public JsonResult UpdateQuantityOfItem(Cart cart, int productID, int quantity)
        {
            var product = mainRepository.Products
                .FirstOrDefault(x => x.ProductID == productID);

            if (product != null)
            {
                cart.Update(product, quantity);
                return Json(1);
            }
            else
            {
                return Json(0);
            }
        }

        public ViewResult Checkout()
        {

            return View();
        }
    }
}

SportStore.WebUI/Controllers/ProductController.cs
using SportStore.Domain;
using SportStore.Domain.Abstract;
using SportStore.Domain.Concrete;
using SportStore.Domain.Entities;
using SportStore.WebUI.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SportStore.WebUI.Controllers
{
    public class ProductController : Controller
    {
        //inject repository
        private IMainRepository mainRepository { get; set; }
        public ProductController(IMainRepository mainRepo)
        {
            mainRepository = mainRepo;
        }
        // GET: Product
        public ViewResult Index(int page = 1, int category = 0)
        {
            ProductIndexViewModel model = new ProductIndexViewModel();

            ViewBag.CategoryId = category;

            model.PagingInfo = new PagingInfo()
            {
                CurrentPage = page,
                ItemsPerPage = 4,
                TotalItems = mainRepository.Products
                .Where(x => category == 0 || x.CategoryID == category)
                .Count()
            };

            model.Products = mainRepository.Products
                .OrderBy(x => x.ProductID)
                .Where(x => category == 0 || x.CategoryID == category)
                .Skip((page - 1) * model.PagingInfo.ItemsPerPage)
                .Take(model.PagingInfo.ItemsPerPage)
                .ToList();

            return View(model);
        }

        public ViewResult Details(int id)
        {
            var model = mainRepository.Products
                .FirstOrDefault(x => x.ProductID == id);
            if (model == null)
            {
                return View("NotFound");
            }

            return View(model);
        }

        public PartialViewResult GetCategories()
        {
            List<Category> model = mainRepository.Categories.ToList();

            return PartialView(model);
        }
    }
}

SportStore.WebUI/Views/Product/Details.cshtml
@model SportsStore.Domain.Entities.Product
@{
    ViewBag.Title = "Chi tiết " + Model.ProductName;
}
<div class="page-header">
    <h3>@Model.ProductName</h3>
</div>
<table class="table table-bordered table-striped">
    <tr>
        <td>
            Giá
        </td>
        <td>
            @Model.Price
        </td>
    </tr>
    <tr>
        <td>
            Số lượng
        </td>
        <td>
            @Model.Amount
        </td>
    </tr>
</table>
<hr />
@Html.Raw(Model.Description);

SportStore.WebUI/Views/Product/GetCategories.cshtml
@model List<SportsStore.Domain.Entities.Category>

<ul class="list-group">
    <li class="list-group-item">
        <a href="@Url.Action("Index", "Product")">
            Tất cả
        </a>
    </li>
    @foreach (var category in Model)
    {
        <li class="list-group-item">
            <a href="@Url.Action("Index", "Product", new { category = category.CategoryID })">
                @category.CategoryName
            </a>
        </li>
    }
</ul>

SportStore.WebUI/Views/Product/Index.cshtml
@model SportStore.WebUI.Models.ProductIndexViewModel

@{
    ViewBag.Title = "Index";
}

<div class="page-header">
    <h3>Product List</h3>
</div>
<div class="row">
    @foreach (var product in Model.Products)
    {
        <div class="col-xs-12 col-sm-3">
            <div class="panel panel-default">
                <div class="panel-body">
                    <img src="@product.ImgUrl" class="img-thumbnail" />
                    <h3 class="product-title">
                        @product.ProductName
                    </h3>
                </div>
                <div class="panel-footer">
                    <div class="row">
                        <div class="col-xs-12 col-sm-6">@product.Price.ToString("C")</div>
                        <div class="col-xs-12 col-sm-6">
                            <a href="@Url.Action("Details","Product", new { id = product.ProductID })">Chi tiết</a>
                            @using (Html.BeginForm("AddTocart", "Cart", FormMethod.Post))
                            {
                                <input type="hidden" value="@product.ProductID" name="ProductID" />
                                <input type="hidden" value="@Request.Url.PathAndQuery" name="ReturnUrl" />
                                <button type="submit" class="btn btn-info">
                                    <i class="glyphicon glyphicon-shopping-cart"></i>
                                </button>
                            }
                        </div>
                    </div>
                </div>
            </div>
        </div>
    }
</div>
<div class="row">
    <div class="col-xs-12">
        @Html.PageLink(Model.PagingInfo, x => Url.Action("Index", "Product", new { page = x, category = ViewBag.CategoryId }))
    </div>
</div>